### ISSUE TITLE
Matrix Example

### ISSUE THREAD

**Issue by kantohm11** [egison/egison-tutorial#13]
[This line ](https://github.com/egison/egison-tutorial/blob/61385dbedcd864cbb98447d9a545aa1a7b727579/Main.hs#L494):
`     ["[| [| 1 2 |] [| 10 20 30 |] |]"`
is supposed to be an example of a matrix. So, it should probably be
`     ["[| [| 1 2 3 |] [| 10 20 30 |] |]"`.

**Comment by egisatoshi** [comment]
Thank you very much! I fixed the mistake.
