### ISSUE TITLE
Approximate value of π²/6

### ISSUE THREAD

**Issue by nekketsuuu** [egison/egison-tutorial#6]
In [this line](https://github.com/egison/egison-tutorial/blob/fa81fd5738ea1d21839ad7a79357fc621d2954ca/Main.hs#L298) of the tutorial, we calculate an approximate value of `(/ (power pi 2) 6)`.

But we can't show the real value of `(/ (power pi 2) 6)` in Egison because `pi` is defined as a symbol `π` and because it seems that Egison doesn't have `f.power` currently.

**Proposal**: Therefore, how about adding a description how to calculate the real value? For example, we can calculate the value by `(f./ (f.* f.pi f.pi) 6.0)`.

**Comment by egisatoshi** [comment]
Thank you for adding the issue!
Yes,  `(/ (power pi 2) 6)` was executable only by the past version of Egison.
I updated this expression to `(f./ (f.* f.pi f.pi) 6.0)` as your proposal.
